### ISSUE TITLE
[Bug] Error Null PlayerKillEvent

### ISSUE THREAD

**Issue by Squesly** [MherZaqaryan/BedWars1058-Cosmetics-Issues#103] opened 2023-05-12 15:44 UTC
**Describe the bug**

**How to reproduce**
1. Playgame
2. Kill someplayer 

**Server Information (please complete the following information):**
 - OS: Linux
 - Server Software: PaperSpigot
 - Software Version: 1.8.8
 - BedWars1058 Version: 22.7
 - Cosmetics Addon: 1.1.2

This error happens randomly

Error:
[15:43:26 ERROR]: Could not pass event PlayerKillEvent to BedWars1058-Cosmetics v1.1.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[server.jar:git-Carbon-0254f60]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-Carbon-0254f60]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Carbon-0254f60]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524) ~[server.jar:git-Carbon-0254f60]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:509) ~[server.jar:git-Carbon-0254f60]
        at com.andrei1058.bedwars.listeners.DamageDeathMove.onDeath(DamageDeathMove.java:453) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor563.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:290) ~[server.jar:git-Carbon-0254f60]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-Carbon-0254f60]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Carbon-0254f60]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524) ~[server.jar:git-Carbon-0254f60]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:509) ~[server.jar:git-Carbon-0254f60]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:445) ~[server.jar:git-Carbon-0254f60]
        at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:511) ~[server.jar:git-Carbon-0254f60]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:889) ~[server.jar:git-Carbon-0254f60]
        at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:846) ~[server.jar:git-Carbon-0254f60]
        at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:650) ~[server.jar:git-Carbon-0254f60]
        at com.andrei1058.bedwars.support.version.v1_8_R3.v1_8_R3.voidKill(v1_8_R3.java:358) ~[?:?]
        at com.andrei1058.bedwars.listeners.DamageDeathMove.onMove(DamageDeathMove.java:624) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor169.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:290) ~[server.jar:git-Carbon-0254f60]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-Carbon-0254f60]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Carbon-0254f60]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524) ~[server.jar:git-Carbon-0254f60]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:509) ~[server.jar:git-Carbon-0254f60]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:390) ~[server.jar:git-Carbon-0254f60]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(PacketPlayInFlying.java:19) ~[server.jar:git-Carbon-0254f60]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(PacketPlayInFlying.java:106) ~[server.jar:git-Carbon-0254f60]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(PlayerConnectionUtils.java:9) ~[server.jar:git-Carbon-0254f60]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:104) ~[server.jar:git-Carbon-0254f60]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:923) ~[server.jar:git-Carbon-0254f60]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:430) ~[server.jar:git-Carbon-0254f60]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:858) ~[server.jar:git-Carbon-0254f60]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:671) ~[server.jar:git-Carbon-0254f60]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:134) ~[server.jar:git-Carbon-0254f60]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.NullPointerException

**Comment by MherZaqaryan** [comment] 2024-01-17 20:24
Thanks for reporting! This error doesn't contain relevant information about the root cause of the issue, and I couldn't reproduce it, please provide a complete log of the error if possible.

**Comment by MherZaqaryan** [comment] 2024-01-23 14:55
This issue will be marked closed as it lacks the information to find the root cause of this error, if you get the same issue on the latest version, please make sure to create a new issue containing the complete error.

**Closed as completed by MherZaqaryan** 2024-01-23 14:55 UTC
Labels: bug
